### PR TITLE
Update Ruby

### PR DESCRIPTION
**Pull request by BronsonQuick**
I tried 1.9.1 but it wouldn't provision so 1.9.3 it is!

### CODE REVIEW

**Comment by rmccue** [comment]
Is this tested and working? In #2, it needed `update-alternatives` as well, which I don't think this covers?

**Comment by BronsonQuick** [comment]
Yeah it's tested and works for me. I wouldn't have submitted it without testing it :+1: You'll note here that it was working earlier in those steps: https://github.com/Chassis/mailcatcher/issues/2#issuecomment-81334977

**Comment by rmccue** [comment]
Cool, just wanted to double-check ;)

Also, we should have `class { 'mailcatcher': }` require this, to ensure the order is correct.

**Comment by javorszky** [comment]
It doesn't work for me.
- cloned Chassis (currently at https://github.com/Chassis/Chassis/commit/9d262544afca3f9e7862b499d27686c5aeea8670)
- cloned mailcatcher as submodule into `extensions/`
- checked out the `ruby-update` branch in mailcatcher
- ran `vagrant up`

The logs:

```
==> default: Notice: /Stage[main]/Main/Package[ruby1.9.3]/ensure: ensure changed 'purged' to 'latest'
==> default: Notice: /Stage[main]/Mailcatcher/Package[libsqlite3-dev]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Mailcatcher/File[/etc/init/mailcatcher.conf]/ensure: defined content as '{md5}2ed1dc648b9c39750a6617e0110a2f71'
==> default: Notice: /Stage[main]/Mailcatcher/Package[g++]/ensure: ensure changed 'purged' to 'present'
==> default: Error: Execution of '/usr/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: Building native extensions.  This could take a while...
==> default: ERROR:  Error installing mailcatcher:
==> default:    ERROR: Failed to build gem native extension.
==> default:
==> default:         /usr/bin/ruby1.9.1 extconf.rb
==> default: creating Makefile
==> default:
==> default: make
==> default: sh: 1: make: not found
==> default:
==> default:
==> default: Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.3 for inspection.
==> default: Results logged to /var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/gem_make.out
==> default: Error: /Stage[main]/Mailcatcher/Package[mailcatcher]/ensure: change from absent to present failed: Execution of '/usr/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: Building native extensions.  This could take a while...
==> default: ERROR:  Error installing mailcatcher:
==> default:    ERROR: Failed to build gem native extension.
==> default:
==> default:         /usr/bin/ruby1.9.1 extconf.rb
==> default: creating Makefile
==> default:
==> default: make
==> default: sh: 1: make: not found
==> default:
==> default:
==> default: Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.3 for inspection.
==> default: Results logged to /var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/gem_make.out
```

**Comment by javorszky** [comment]
If I update `update-alternatives` as per https://github.com/Chassis/mailcatcher/issues/2#issuecomment-81331995 and then reprovision, then it works. But not on a clean install.

**Comment by Mamaduka** [comment]
This doesn't work without `sudo update-alternatives --config ruby` and another provision. @BronsonQuick @rmccue any ideas how to fix it?

Sorry lack experience with Puppet, but will be happy to send PR, if you can point me to right direction.

**Comment by BronsonQuick** [comment]
@Mamaduka It's been a while since I used our mailcatcher extension so I didn't realise it's broken still :-1: I'm thinking that the right direction for solving this with puppet is something like https://github.com/puppet-community/puppet-alternatives/issues/9#issuecomment-45253335 but I haven't tried or tested it. Let me know if you have any luck. I'd love a PR to fix this. Thanks!

**Comment by rmccue** [comment]
@Mamaduka Can you give MailHog a try instead? https://github.com/Chassis/MailHog

MailHog is Go-based, but even better, they ship binaries instead of Ruby packages, so it's unlikely we'll hit into issues again there.

If that works, I might deprecate Mailcatcher in favour of MailHog.

**Comment by Mamaduka** [comment]
@rmccue was thinking about MailHog, since John tweeted about it. It doesn't have puppet module, but I think I can convert bash script.

**Comment by rmccue** [comment]
@Mamaduka I already made an extension, see the link above :)

**Comment by Mamaduka** [comment]
@rmccue ugh, sorry thought it was original MailHog repo. Testing it now, and

Nooice

**Comment by BronsonQuick** [comment]
Alrighty. We're no longer maintaining this so I'm closing this off: https://github.com/Chassis/Chassis/pull/236#issuecomment-247811035

**Pull request closed without merging**
